"use client";
import Link from "next/link";
import { useState } from "react";
import { Icon } from "@/components/Icons";
import { SiteShell } from "@/components/SiteShell";
import { HomeFaq } from "@/components/HomeFaq";
import { whatsappUrl } from "@/lib/site-config";

const journeySteps = [
  ["01", "Escuta sem julgamento", "Entendemos o momento, quem precisa de ajuda e o que já foi tentado."],
  ["02", "Orientação individual", "Explicamos possibilidades e limites com linguagem clara e humana."],
  ["03", "Curadoria responsável", "Comparamos perfil, reputação, localização, disponibilidade, estrutura e viabilidade."],
  ["04", "A família decide", "Apresentamos opções compatíveis. A decisão e o contrato são sempre da família com a clínica."],
];

export default function Home() {
  const [clinic, setClinic] = useState("A definir após avaliação");
  const [problem, setProblem] = useState("Álcool");
  const [admission, setAdmission] = useState("Ainda não sei");
  const message = `Olá, preciso de orientação da New Journey.\nProblema principal: ${problem}\nTipo de internação: ${admission}\nClínica: ${clinic}`;
  return <SiteShell>
    <section className="home-hero"><div className="hero-art" aria-hidden="true"/><div className="hero-wash"/><div className="hero-inner"><span className="kicker kicker-light">ATENDIMENTO HUMANO 24 HORAS</span><h1>Você não precisa encontrar todas as respostas <em>sozinho.</em></h1><p>Orientamos pessoas e famílias a compreender o momento, avaliar caminhos e tomar uma decisão segura sobre o cuidado com álcool e outras drogas.</p><div className="hero-buttons"><Link className="btn btn-mint" href="/agendamento">Quero conversar agora <Icon name="arrow"/></Link><Link className="btn btn-outline-light" href="/tratamentos">Entender as possibilidades</Link></div><div className="hero-trust"><span><Icon name="clock"/> Disponível 24h</span><span><Icon name="shield"/> Conversa confidencial</span><span><Icon name="heart"/> Sem pressão comercial</span></div></div></section>
    <section className="guided-search" aria-labelledby="busca-titulo"><div className="guided-copy"><span className="kicker">ORIENTAÇÃO INICIAL</span><h2 id="busca-titulo">Conte o essencial. Nós ajudamos no próximo passo.</h2><p>Esta seleção não dá diagnóstico nem indica automaticamente uma clínica. Ela prepara uma conversa mais clara com o orientador.</p></div><div className="guided-form"><label>Clínica parceira<select value={clinic} onChange={e=>setClinic(e.target.value)}><option>A definir após avaliação</option><option>Clínica parceira 01 — cadastro pendente</option><option>Clínica parceira 02 — cadastro pendente</option></select><small>Dados reais serão adicionados após homologação.</small></label><label>Problema principal<select value={problem} onChange={e=>setProblem(e.target.value)}><option>Álcool</option><option>Cocaína ou crack</option><option>Maconha</option><option>Medicamentos</option><option>Uso de múltiplas substâncias</option><option>Outro ou ainda não sei</option></select></label><label>Possibilidade de internação<select value={admission} onChange={e=>setAdmission(e.target.value)}><option>Ainda não sei</option><option>Voluntária — com consentimento</option><option>Involuntária — sem consentimento</option><option>Quero apenas orientação</option></select></label><a className="btn btn-dark" href={whatsappUrl(message)} target="_blank" rel="noreferrer">Levar seleção ao WhatsApp <Icon name="arrow"/></a></div></section>
    <section className="entry-paths section-pad"><div className="section-heading"><span className="kicker">POR ONDE COMEÇAR</span><h2>Existe um caminho para cada momento.</h2><p>Escolha o ponto que mais se aproxima da situação atual.</p></div><div className="path-grid"><Link href="/familias"><Icon name="family" size={28}/><h3>Busco ajuda para um familiar</h3><p>Como conversar, estabelecer limites e procurar cuidado sem enfrentar tudo sozinho.</p><span>Ver orientação <Icon name="arrow"/></span></Link><Link href="/agendamento"><Icon name="heart" size={28}/><h3>Busco ajuda para mim</h3><p>Uma primeira conversa acolhedora, respeitando seu tempo e suas escolhas.</p><span>Falar em confiança <Icon name="arrow"/></span></Link><Link href="/tratamentos"><Icon name="compass" size={28}/><h3>Quero entender o tratamento</h3><p>Veja diferenças entre cuidado ambulatorial, acolhimento e internação.</p><span>Conhecer caminhos <Icon name="arrow"/></span></Link><Link href="/agendamento?urgente=1" className="urgent-card"><Icon name="phone" size={28}/><h3>Existe uma situação urgente</h3><p>Identifique sinais de risco e procure o serviço adequado imediatamente.</p><span>Ver apoio urgente <Icon name="arrow"/></span></Link></div></section>
    <section className="journey section-pad"><div className="journey-intro"><span className="kicker kicker-light">COMO FUNCIONA</span><h2>Clareza antes de qualquer decisão.</h2><p>A New Journey não é clínica e não promete cura. Somos uma orientação humana entre a dúvida da família e a escolha consciente de um serviço compatível.</p><Link href="/sobre">Conheça nossos critérios <Icon name="arrow"/></Link></div><div className="journey-list">{journeySteps.map(([n,title,text])=><article key={n}><span>{n}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
    <section className="family-feature section-pad"><div className="family-photo" role="img" aria-label="Família adulta em conversa acolhedora"><blockquote>“A família também precisa de cuidado durante e depois do tratamento.”</blockquote></div><div className="family-feature-copy"><span className="kicker">CUIDADO QUE CONTINUA</span><h2>Amparo para quem está ao lado.</h2><p>A dependência afeta relações, rotina, finanças e segurança emocional. Por isso, ajudamos a família a compreender o processo, organizar perguntas e tomar decisões sem culpa ou pressão.</p><ul><li><Icon name="check"/> Orientação antes de escolher o serviço</li><li><Icon name="check"/> Acompanhamento após o encaminhamento</li><li><Icon name="check"/> Comunicação clara durante cada etapa</li></ul><Link className="text-link" href="/familias">Conhecer o atendimento familiar <Icon name="arrow"/></Link></div></section>
    <section className="public-care section-pad"><div><span className="kicker">TRANSPARÊNCIA</span><h2>Internação não é a única possibilidade.</h2></div><p>Dependendo da situação, serviços públicos como CAPS AD, unidades de saúde e urgência também podem ser o caminho adequado. Nossa orientação considera segurança, necessidade, contexto e viabilidade — não apenas uma vaga disponível.</p><Link className="btn btn-outline-dark" href="/tratamentos">Comparar possibilidades</Link></section>
    <section className="final-cta"><span className="kicker kicker-light">O PRIMEIRO PASSO PODE SER UMA CONVERSA</span><h2>Você não precisa decidir tudo hoje.</h2><p>Agende em qualquer horário ou fale agora pelo WhatsApp. Sem julgamento e sem compromisso de internação.</p><Link className="btn btn-mint" href="/agendamento">Agendar conversa 24h <Icon name="arrow"/></Link></section>
    <HomeFaq />
  </SiteShell>;
}
